// Reads narration out loud: one mp3 per slide per language, from manus.<språk>.json.
//
//   node tools/pptx-til-leksjon/tale.js leksjon --sprak no,lt
//
// Uses ElevenLabs' multilingual model, which covers all five of the app's languages (no/en/lt/lv/ru)
// with one voice — so the same narrator reads the lesson whatever language it is played in, instead
// of five people of five different genders and registers. ELEVENLABS_API_KEY lives in this repo's
// local .env and is never needed on Render: no audio is ever generated by the server, only uploaded
// to it.
//
// Only generate the languages the people who will take the course actually read. Audio is the bulk
// of a lesson's disk footprint, and Render's volume is one gigabyte shared with the database and
// every photo the app has ever stored — `GET /auth/users` shows each account's language.
import fs from "node:fs";
import path from "node:path";
import "dotenv/config";

const MODEL = "eleven_multilingual_v2";
// Any ElevenLabs voice id; this is their "Charlotte", picked as a calm, unhurried default. Override
// with --stemme <id> to use a voice from the account's own library.
const DEFAULT_VOICE = "XB0fDUnXU5powFXDhCwa";

const [dir, ...rest] = process.argv.slice(2);
if (!dir) {
  console.error("Bruk: node tools/pptx-til-leksjon/tale.js <mappe> [--sprak no,lt] [--stemme <voice id>]");
  process.exit(1);
}

const flag = (name, fallback) => (rest.includes(name) ? rest[rest.indexOf(name) + 1] : fallback);
const languages = flag("--sprak", "no").split(",").map((l) => l.trim()).filter(Boolean);
const voiceId = flag("--stemme", DEFAULT_VOICE);

const apiKey = process.env.ELEVENLABS_API_KEY;
if (!apiKey) {
  console.error("ELEVENLABS_API_KEY mangler i .env — den trengs for å lage tale.");
  process.exit(1);
}

async function speak(text) {
  const res = await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${voiceId}`, {
    method: "POST",
    headers: { "xi-api-key": apiKey, "Content-Type": "application/json" },
    body: JSON.stringify({
      text,
      model_id: MODEL,
      // Speech at a modest bitrate: this is a voice in a noisy building through a phone speaker,
      // not music, and the difference between 64 and 128 kbps is a lot of disk for nothing.
      output_format: "mp3_44100_64",
      voice_settings: { stability: 0.5, similarity_boost: 0.75 },
    }),
  });
  if (!res.ok) throw new Error(`ElevenLabs svarte ${res.status}: ${await res.text()}`);
  return Buffer.from(await res.arrayBuffer());
}

let totalChars = 0;
for (const language of languages) {
  const manusPath = path.join(dir, `manus.${language}.json`);
  if (!fs.existsSync(manusPath)) {
    console.error(`Fant ikke ${manusPath} — kjør manus.js for ${language} først.`);
    process.exit(1);
  }
  const slides = JSON.parse(fs.readFileSync(manusPath, "utf8"));
  const outDir = path.join(dir, "lyd", language);
  fs.mkdirSync(outDir, { recursive: true });

  for (const slide of slides) {
    const target = path.join(outDir, `slide-${String(slide.index).padStart(2, "0")}.mp3`);
    if (!slide.narration) {
      console.warn(`  ${language} lysbilde ${slide.index}: tomt manus, hopper over`);
      continue;
    }
    // Skips what is already there, so a rerun after fixing two slides costs two API calls rather
    // than the whole lesson. Delete the mp3 for a slide you have rewritten.
    if (fs.existsSync(target)) {
      console.log(`  ${language} lysbilde ${slide.index}: finnes fra før`);
      continue;
    }
    process.stdout.write(`  ${language} lysbilde ${slide.index} … `);
    fs.writeFileSync(target, await speak(slide.narration));
    totalChars += slide.narration.length;
    console.log("ok");
  }
}

console.log(`\nFerdig. ${totalChars} tegn lest inn (det er dette ElevenLabs fakturerer etter).`);
